// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "aifriend/internal/handler/auth"
	character "aifriend/internal/handler/character"
	user "aifriend/internal/handler/user"
	"aifriend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// 刷新Token
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				// 获取头像文件
				Method:  http.MethodGet,
				Path:    "/uploads/avatars/:filename",
				Handler: user.ServeAvatarHandler(serverCtx),
			},
			{
				// 获取角色头像文件
				Method:  http.MethodGet,
				Path:    "/uploads/characters/:filename",
				Handler: character.ServeCharacterImageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建角色
				Method:  http.MethodPost,
				Path:    "/character",
				Handler: character.CreateCharacterHandler(serverCtx),
			},
			{
				// 获取单个角色
				Method:  http.MethodGet,
				Path:    "/character/:id",
				Handler: character.GetCharacterHandler(serverCtx),
			},
			{
				// 更新角色
				Method:  http.MethodPut,
				Path:    "/character/:id",
				Handler: character.UpdateCharacterHandler(serverCtx),
			},
			{
				// 删除角色
				Method:  http.MethodDelete,
				Path:    "/character/:id",
				Handler: character.RemoveCharacterHandler(serverCtx),
			},
			{
				// 获取角色列表
				Method:  http.MethodGet,
				Path:    "/character/list",
				Handler: character.GetCharacterListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 上传头像
				Method:  http.MethodPost,
				Path:    "/user/avatar",
				Handler: user.UploadAvatarHandler(serverCtx),
			},
			{
				// 获取当前用户信息
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				// 更新用户信息
				Method:  http.MethodPut,
				Path:    "/user/info",
				Handler: user.UpdateUserInfoHandler(serverCtx),
			},
			{
				// 修改密码
				Method:  http.MethodPost,
				Path:    "/user/password",
				Handler: user.ChangePasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
